In [ ]:
'''
Part 1: Theoretical Questions

Q1: What are the different data structures used in TensorFlow? Give some examples.
A1: TensorFlow uses tensors as the main data structure. Tensors are multi-dimensional arrays used to represent and perform computations on data. There are three commonly used types of tensors in TensorFlow:
Scalar: A scalar tensor represents a single value, such as a number or a constant.
Vector: A vector tensor represents a one-dimensional array of values. It can be thought of as a list of numbers.
Matrix: A matrix tensor represents a two-dimensional array of values, arranged in rows and columns.
Examples:
Scalar: 3, 2.5, -1
Vector: [1, 2, 3], [0.5, 1.5, 2.5, 3.5]
Matrix: [[1, 2], [3, 4]], [[0.5, 1.5, 2.5], [-1, 0, 1]]

Q2: How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
A2: In TensorFlow, a constant is a type of tensor whose value cannot be changed once it is defined. It is used to represent fixed values that remain constant throughout the execution of a program. Constants are typically used to define model parameters or fixed inputs.
On the other hand, a variable is a type of tensor whose value can be modified during the execution of a program. Variables are used to represent trainable parameters, such as the weights and biases in a neural network. They can be updated and optimized during the training process.
Example:
    
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
c = a + b
x = tf.Variable(5)
y = tf.Variable(10)
z = x * y
In the above example, a and b are constants with fixed values, while x and y are variables that can be modified. The constant c
represents the sum of a and b, which is computed once and remains unchanged. The variable z represents the product of x and y, which can
be modified and updated.

Q3: Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
A3:Matrix Addition: In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator. It adds corresponding elements of two matrices together. The matrices must have the same dimensions.
Example:
import tensorflow as tf
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.add(A, B)

Matrix Multiplication: Matrix multiplication in TensorFlow can be performed using the tf.matmul() function or the @ operator. It computes the dot product of two matrices. The number of columns in the first matrix must be equal to the number of rows in the second matrix.
Example:
import tensorflow as tf
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
D = tf.matmul(A, B)

Element-wise Operations: Element-wise operations perform operations on corresponding elements of two matrices or tensors. TensorFlow provides various element-wise operations such as addition, subtraction, multiplication, division, exponentiation, etc. These operations are applied independently to each element of the matrices.
Example:
import tensorflow as tf
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
# Element-wise add
D = tf.add(A, B)
# Element-wise multiplication
E = tf.multiply(A, B)
# Element-wise division
F = tf.divide(A, B
# Element-wise exponentiation
G = tf.pow(A, B)
'''

### Part 2: Practical Implementation### 

In [2]:
# Task 1: Creating and Manipulating Matrices
import tensorflow as tf

# Create a normal matrix A with dimensions 2x2 using random_normal function
A = tf.random.normal(shape=(2, 2))
print("Matrix A:")
print(A.numpy())

# Create a Gaussian matrix B with dimensions 3x3 using truncated_normal function
B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B:")
print(B.numpy())

# Create a matrix C with dimensions 2x2, drawn from a normal distribution
mean = 2.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("Matrix C:")
print(C.numpy())

# Perform matrix addition between matrix A and matrix B
D = tf.add(A, B)
print("Matrix D (A + B):")
print(D.numpy())

# Perform matrix multiplication between matrix C and matrix D
E = tf.matmul(C, D)
print("Matrix E (C * D):")
print(E.numpy())


Matrix A:
[[ 1.4355335   0.08528771]
 [ 1.0933864  -0.5701154 ]]
Matrix B:
[[-1.0816008  -0.8890279 ]
 [ 0.83037657  0.6354611 ]]
Matrix C:
[[1.7548909 1.4465413]
 [2.7321253 2.299282 ]]
Matrix D (A + B):
[[ 0.35393274 -0.8037402 ]
 [ 1.923763    0.0653457 ]]
Matrix E (C * D):
[[ 3.4039161 -1.3159511]
 [ 5.3902626 -2.0456707]]


In [3]:
#Task 2: Performing Additional Matrix Operations
import tensorflow as tf

# Create a matrix F with dimensions 2x2, initialized with random values using random_uniform function
F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(F.numpy())

# Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)
print("Matrix G (Transpose of F):")
print(G.numpy())

# Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F):")
print(H.numpy())

# Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (Concatenation of F and G horizontally):")
print(I.numpy())

# Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (Concatenation of F and H vertically):")
print(J.numpy())


Matrix F:
[[0.99757457 0.32296622]
 [0.5712143  0.5822034 ]]
Matrix G (Transpose of F):
[[0.99757457 0.5712143 ]
 [0.32296622 0.5822034 ]]
Matrix H (Element-wise Exponential of F):
[[2.7116969 1.3812187]
 [1.7704155 1.7899781]]
Matrix I (Concatenation of F and G horizontally):
[[0.99757457 0.32296622 0.99757457 0.5712143 ]
 [0.5712143  0.5822034  0.32296622 0.5822034 ]]
Matrix J (Concatenation of F and H vertically):
[[0.99757457 0.32296622]
 [0.5712143  0.5822034 ]
 [2.7116969  1.3812187 ]
 [1.7704155  1.7899781 ]]
